packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**/!(dist)/**'
  - 'packages/**/!(loader)/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/storybook-static/**'
